ALTER TABLE fornecedor 
    ADD COLUMN IF NOT EXISTS documento VARCHAR(18),
    ADD COLUMN IF NOT EXISTS inscricao_estadual VARCHAR(20),
    ADD COLUMN IF NOT EXISTS razao_social VARCHAR(100) NOT NULL,
    ADD COLUMN IF NOT EXISTS nome_fantasia VARCHAR(100),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;


ALTER TABLE pessoa_telefones
    RENAME COLUMN telefone TO telefones;

ALTER TABLE pessoa_emails
    RENAME COLUMN email TO emails;